vars:
  VERSION:
    default: 1.0.0
  BUILD_NUMBER:
    default: 1
  DISPLAY_NAME:
    default: 'Case of the Century: The Forbidden Couple'
  BUNDLE_ID:
    default: com.joazco.caseofthecenturytheforbiddencouple
platforms:
  android:
    packageName: $BUNDLE_ID
    appName: $DISPLAY_NAME
    versionName: $VERSION
    versionCode: $BUILD_NUMBER
  ios:
    targets:
      App:
        displayName: $DISPLAY_NAME
        bundleId: $BUNDLE_ID
        version: $VERSION
        buildNumber: $BUILD_NUMBER
        plist:
          replace: true
          entries:
            - CFBundleName: $DISPLAY_NAME
            - CFBundleShortVersionString: $VERSION
            - UIViewControllerBasedStatusBarAppearance: false
            - UIStatusBarHidden: true
            - UISupportedInterfaceOrientations:
                - UIInterfaceOrientationLandscapeLeft
                - UIInterfaceOrientationLandscapeRight
            - UISupportedInterfaceOrientations~ipad:
                - UIInterfaceOrientationLandscapeLeft
                - UIInterfaceOrientationLandscapeRight
            - UIRequiresFullScreen: true
