export { default as PageComponent } from "./PageComponent";
export { default as TranslationComponent } from "./TranslationComponent";
export { default as GlobalCSSComponent } from "./GlobalCSSComponent";
export { default as SpriteComponent } from "./SpriteComponent";
export { default as ImgComponent } from "./ImgComponent";
export { default as AnimationComponent } from "./AnimationComponent";
export { default as ImgFromSpriteComponent } from "./ImgFromSpriteComponent";
export { default as CanvasImageComponent } from "./CanvasImageComponent";
export { default as VisualNovelTextComponent } from "./VisualNovelTextComponent";
